// ASP.NET Core Basics/src/Angular/ClientApp/app/components/contacts/contactdetail.component.ts
﻿import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute, Params } from '@angular/router';
import 'rxjs/add/operator/switchMap';
import { Contact } from './contact';
import { ContactService } from './contact.service';

@Component({
    selector: 'contactdetail',
    template: './contactdetail.component.html',
    providers: [ContactService]
})
export class ContactDetailComponent implements OnInit {
    contact: Contact = new Contact();
    hasContactId: boolean;

    constructor(private route: ActivatedRoute,
                private router: Router,
                private contactService: ContactService) { }

    ngOnInit(): void {
        var contactId: string;

        this.route.params
            .subscribe((params: Params) => contactId = params['id']);
        this.hasContactId = contactId != undefined;

        if (this.hasContactId) {
            this.contactService.getById(contactId)
                .then((contact: Contact) => this.contact = contact);
        }
    }

    reset() {
        this.contact = new Contact();
    }

    save() {
        this.contactService.save(this.contact)
            .then(contact => this.contact = contact)
            .then(() => this.hasContactId = true);
    }
}
﻿<h1>Contact Details</h1>
<hr />
<div *ngIf="hasContactId">
    <dl class="dl-horizontal">
        <dt>ID</dt>
        <dd>{{contact.id}}</dd>
        <dt>Name</dt>
        <dd>{{contact.name}}</dd>
        <dt>Address</dt>
        <dd>{{contact.getAddress()}}</dd>
        <dt>Phone</dt>
        <dd>{{contact.phone}}</dd>
        <dt>Email</dt>
        <dd>{{contact.email}}</dd>
    </dl>
</div>
<div *ngIf="!hasContactId">
    <div>
        <form role="form" class="form-horizontal">
            <div class="form-group">
                <label class="col-sm-2 control-label">Name</label>
                <div class="col-sm-10">
                    <input type="text" placeholder="name" class="form-control" [(ngModel)]="contact.name" name="name" />
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Address</label>
                <div class="col-sm-10">
                    <input type="text" placeholder="address" class="form-control" [(ngModel)]="contact.address" name="address" />
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">City</label>
                <div class="col-sm-10">
                    <input type="text" placeholder="city" class="form-control" [(ngModel)]="contact.city" name="city" />
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">State</label>
                <div class="col-sm-10">
                    <input type="text" placeholder="state" class="form-control" [(ngModel)]="contact.state" name="state" />
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Zip</label>
                <div class="col-sm-10">
                    <input type="text" placeholder="zip" class="form-control" [(ngModel)]="contact.postalCode" name="postalCode" />
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Phone</label>
                <div class="col-sm-10">
                    <input type="text" placeholder="phone" class="form-control" [(ngModel)]="contact.phone" name="phone" />
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Email</label>
                <div class="col-sm-10">
                    <input type="email" placeholder="email" class="form-control" [(ngModel)]="contact.email" name="email" />
                </div>
            </div>
        </form>
    </div>
    <div class="text-center">
        <button class="btn btn-success btn-lg" (click)="save()">Save</button>
        <button class="btn btn-danger btn-lg" (click)="reset()">Reset</button>
    </div>
</div>
<a routerLink="/contact-list">Back to List</a>
<hr />

// ASP.NET Core Basics/src/React/ClientApp/components/contacts/ContactDetail.tsx
﻿import * as React from 'react';
import { RouteComponentProps } from 'react-router';
import { NavLink } from 'react-router-dom';
import 'isomorphic-fetch';
import { Contact } from './contact';
import { ContactService } from './contactService';

interface ContactDetailState {
    id: string;
    contact: Contact;
    loading: boolean;
}

export class ContactDetail extends React.Component<RouteComponentProps<{}>, ContactDetailState> {

    constructor(props: any) {
        super();


        if (props.match.params.id == undefined) {
            this.state = { id: props.match.params.id, contact: new Contact(), loading: false };
        }
        else {
            this.state = { id: props.match.params.id, contact: new Contact(), loading: true };

            let contactService = new ContactService();
            contactService.getById(this.state.id)
                .then(data => {
                    this.setState({ contact: data, loading: false });
                });
        }
    }

    public render() {
        let contents = this.state.loading
            ? <p><em>Loading...</em></p>
            : this.state.id != undefined
                ? ContactDetail.renderExistingContact(this.state.contact)
                : this.renderNewContact();

        return <div>
            <h1>Contact Detail</h1>
            <hr />
            {contents}
            <NavLink to={'/contactlist'}>Back to List</NavLink>
            <hr />
        </div>;
    }

    private static renderExistingContact(contact: Contact) {
        return <dl className="dl-horizontal">
            <dt>ID</dt>
            <dd>{contact.id}</dd>
            <dt>Name</dt>
            <dd>{contact.name}</dd>
            <dt>Address</dt>
            <dd>{contact.getAddress()}</dd>
            <dt>Phone</dt>
            <dd>{contact.phone}</dd>
            <dt>Email</dt>
            <dd>{contact.email}</dd>
        </dl>;
    }

    private reset() {
        this.setState({ contact: new Contact() });
    }

    private renderNewContact() {
        return (
            <div>
                <form role="form" className="form-horizontal">
                    <div className="form-group">
                        <label className="col-sm-2 control-label">Name</label>
                        <div className="col-sm-10">
                            <input type="text" placeholder="name" className="form-control" value={this.state.contact.name} />
                        </div>
                    </div>
                    <div className="form-group">
                        <label className="col-sm-2 control-label">Address</label>
                        <div className="col-sm-10">
                            <input type="text" placeholder="address" className="form-control" value={this.state.contact.address} />
                        </div>
                    </div>
                    <div className="form-group">
                        <label className="col-sm-2 control-label">City</label>
                        <div className="col-sm-10">
                            <input type="text" placeholder="city" className="form-control" value={this.state.contact.city} />
                        </div>
                    </div>
                    <div className="form-group">
                        <label className="col-sm-2 control-label">State</label>
                        <div className="col-sm-10">
                            <input type="text" placeholder="state" className="form-control" value={this.state.contact.state} />
                        </div>
                    </div>
                    <div className="form-group">
                        <label className="col-sm-2 control-label">Zip</label>
                        <div className="col-sm-10">
                            <input type="text" placeholder="zip" className="form-control" value={this.state.contact.postalCode} />
                        </div>
                    </div>
                    <div className="form-group">
                        <label className="col-sm-2 control-label">Phone</label>
                        <div className="col-sm-10">
                            <input type="text" placeholder="phone" className="form-control" value={this.state.contact.phone} />
                        </div>
                    </div>
                    <div className="form-group">
                        <label className="col-sm-2 control-label">Email</label>
                        <div className="col-sm-10">
                            <input type="email" placeholder="email" className="form-control" value={this.state.contact.email} />
                        </div>
                    </div>
                </form>
                <div className="text-center">
                    <button className="btn btn-success btn-lg" type="submit">Save</button>
                    <button className="btn btn-danger btn-lg" onClick={() => this.reset()}>Reset</button>
                </div >
            </div>
        );
    }

}
